---
- name: restart daemons
  local_action: command /bin/true
  notify:
          - restart kubelet
          - restart proxy

- name: restart cadvisor
  service: name=cadvisor state=restarted

- name: restart kubelet
  service: name=kubelet state=restarted

- name: restart proxy
  service: name=kube-proxy state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: restart docker
  service: name=docker state=restarted

# OK, so it really reboots, sue me
- name: restart network
  command: shutdown -r now
