---
- name: restart daemons
  command: /bin/true
  notify:
          - restart kubelet
          - restart proxy

- name: restart cadvisor
  service: name=cadvisor state=restarted

- name: restart kubelet
  service: name=kubelet state=restarted

- name: restart proxy
  service: name=kube-proxy state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: restart docker
  command: /bin/sh -c 'systemctl stop docker && ip link delete docker0 && systemctl start docker'
