---
- name: Create kubernetes bridge interface
  command: nmcli connection add type bridge ifname kbr0 con-name kubernetes-bridge save yes ip4 {{ kube_ip_addr }}/24
  args:
        creates: /etc/sysconfig/network-scripts/ifcfg-kubernetes-bridge

- name: Configure docker to use the bridge inferface
  copy: src=docker dest=/etc/sysconfig/docker
