---
- name: Install flannel
  yum: name=flannel state=latest
  when: not is_atomic

- name: Install Flannel config file
  template: src=flanneld.j2 dest=/etc/sysconfig/flanneld
  notify:
          - restart flannel

- name: Launch Flannel
  service: name=flanneld state=started enabled=yes
  notify:
          - stop docker
          - delete docker0
          - start docker
          - restart kubelet
