---
- name: Register for RHEL7
  redhat_subscription: state=present username="{{ lookup('file', '~/rhn_username') }}" password="{{ lookup('file', '~/rhn_password') }}" autosubscribe=true

- name: Enable RHEL7 Extra Repo
  command: "subscription-manager repos --enable rhel-7-server-extras-rpms"
  when: not is_atomic
