---
- name: Copy minion definition to masters
  template: src=node.j2 dest=/tmp/node-{{ item }}.yml
  changed_when: false
  with_items:
          groups['minions']

- name: Load minion definition into masters
  command: /usr/bin/kubectl create -f /tmp/node-{{ item }}.yml
  register: command_result
  failed_when: "'already exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "command_result.rc == 0"
  with_items:
          groups['minions']

- name: Delete minion definitions from masters
  file: path=/tmp/node-{{ item }}.yml state=absent
  changed_when: false
  with_items:
          groups['minions']

- include: firewalld.yml
  when: has_firewalld.rc == 0

- include: iptables.yml
  when: has_firewalld.rc != 0 and has_iptables.rc == 0
