---
- name: write the config files for api server
  template: src=apiserver.j2 dest=/etc/kubernetes/apiserver
  notify:
          - restart apiserver
          - restart controller-manager
          - restart scheduler

- name: write the new style config file for controller-manager
  template: src=controller-manager.j2 dest=/etc/kubernetes/controller-manager
  when: kube_node_via_api
  notify:
          - restart controller-manager
  tags: load_nodes

- name: write the old style config file for controller-manager
  template: src=controller-manager-old.j2 dest=/etc/kubernetes/controller-manager
  when: not kube_node_via_api
  notify:
          - restart controller-manager

- name: write the config file for scheduler
  copy: src=scheduler dest=/etc/kubernetes/scheduler
  notify:
          - restart scheduler

- name: Enable apiserver
  service: name=kube-apiserver enabled=yes state=started

- name: Enable controller-manager
  service: name=kube-controller-manager enabled=yes state=started

- name: Enable scheduler
  service: name=kube-scheduler enabled=yes state=started

- include: load_nodes.yml
  when: kube_node_via_api and not is_aws
  tags: load_nodes

- include: firewalld.yml
  when: has_firewalld.rc == 0

- include: iptables.yml
  when: has_firewalld.rc != 0 and has_iptables.rc == 0

- include: aws.yml
  when: is_aws
